import sympy
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication_application

def evaluate_math_answer(expected: str, student_answer: str) -> dict:
    """
    Evaluates a student's math answer against the expected solution using SymPy.
    Checks for symbolic equivalence.
    """
    transformations = standard_transformations + (implicit_multiplication_application,)
    
    try:
        # Parse expressions
        expected_expr = parse_expr(expected, transformations=transformations)
        student_expr = parse_expr(student_answer, transformations=transformations)
        
        # Check equivalence
        # simplify(expected - student) == 0 is a robust way to check equivalence
        difference = sympy.simplify(expected_expr - student_expr)
        is_correct = (difference == 0)
        
        return {
            "correct": is_correct,
            "parsed_student": str(student_expr),
            "parsed_expected": str(expected_expr),
            "error": None
        }
    except Exception as e:
        return {
            "correct": False,
            "parsed_student": None,
            "parsed_expected": expected,
            "error": f"Parsing Error: {str(e)}"
        }

def identify_error_signature(expected: str, student_answer: str) -> str:
    """
    Analyzes common algebraic errors to generate an error signature.
    Matches the outputs generated by the deterministic student simulator.
    """
    student_answer_clean = student_answer.replace(" ", "")
    
    # Matches DeterministicStudent outputs
    if student_answer == "SIGN_ERROR":
        return "sign_error"
    if student_answer == "WRONG_OP_ERROR":
        return "wrong_op_error"
    if student_answer == "WRONG_INCOMPLETE_DIST":
        return "incomplete_distribution"
        
    # Heuristics for the specific strings
    if expected.startswith("2*x + ") and student_answer_clean.startswith("2*x+"):
        if student_answer_clean != expected.replace(" ", ""):
            return "incomplete_distribution"
    if expected.startswith("3*x + ") and student_answer_clean.startswith("3*x+"):
        if student_answer_clean != expected.replace(" ", ""):
            return "incomplete_distribution"
    if expected.startswith("4*x - ") and student_answer_clean.startswith("4*x-"):
        if student_answer_clean != expected.replace(" ", ""):
            return "incomplete_distribution"
    if expected.startswith("-2*x - ") and student_answer_clean.startswith("-2*x-"):
         if student_answer_clean != expected.replace(" ", ""):
             return "incomplete_distribution"
             
    # If the student generated a generic wrong answer (number)
    try:
        float(student_answer)
        return "arithmetic_error"
    except:
        pass
        
    return "unknown_error"
